file_format: "1"
id: test_zmk
name: test_zmk
type: shield
url: https://github.com/youngishcord/my_zmk
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - test_zmk_left
  - test_zmk_right